-- MySQL Script generated by MySQL Workbench
-- Sat Dec 17 19:39:31 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema events4u
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema events4u
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `events4u` DEFAULT CHARACTER SET utf8mb4 ;
USE `events4u` ;

-- -----------------------------------------------------
-- Table `events4u`.`empresas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `events4u`.`empresas` (
  `id_empresa` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(30) NOT NULL,
  `email` VARCHAR(42) NOT NULL,
  `senha` LONGTEXT NOT NULL,
  `telefone` VARCHAR(12) NOT NULL,
  `cnpj` VARCHAR(18) NOT NULL,
  `cidade` VARCHAR(45) NOT NULL,
  `estado` VARCHAR(45) NOT NULL,
  `foto` VARCHAR(100) NOT NULL DEFAULT 'foto-perfil/padrão.jpg',
  `data_registro` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `online` INT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`id_empresa`),
  UNIQUE INDEX `cnpj_UNIQUE` (`cnpj` ASC) )
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `events4u`.`eventos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `events4u`.`eventos` (
  `id_evento` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(30) NOT NULL,
  `tipo_evento` VARCHAR(15) NOT NULL,
  `data_evento` DATE NOT NULL,
  `local_evento` VARCHAR(100) NOT NULL,
  `cidade` VARCHAR(45) NOT NULL,
  `qtd_promoter` INT NOT NULL,
  `n_seguidores` INT(20) NOT NULL,
  `data_registro` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `id_empresa` INT NOT NULL,
  PRIMARY KEY (`id_evento`),
  INDEX `fk_eventos_empresas1_idx` (`id_empresa` ASC) ,
  CONSTRAINT `fk_eventos_empresas1`
    FOREIGN KEY (`id_empresa`)
    REFERENCES `events4u`.`empresas` (`id_empresa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `events4u`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `events4u`.`usuarios` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(42) NOT NULL,
  `senha` LONGTEXT NOT NULL,
  `telefone` VARCHAR(12) NOT NULL,
  `sexo` VARCHAR(10) NOT NULL,
  `instagram` VARCHAR(50) NOT NULL,
  `tipo_evento` VARCHAR(50) NOT NULL,
  `data_nascimento` DATE NOT NULL,
  `cidade` VARCHAR(45) NOT NULL,
  `estado` VARCHAR(45) NOT NULL,
  `foto` VARCHAR(100) NOT NULL DEFAULT 'foto-perfil/padrão.jpg',
  `cpf` INT(14) NOT NULL,
  `data_registro` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `online` INT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`id_usuario`),
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC) )
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `events4u`.`Atracao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `events4u`.`Atracao` (
  `id_atracao` INT NOT NULL AUTO_INCREMENT,
  ` nm_atracao` VARCHAR(45) NOT NULL,
  `dt_atracao` DATE NOT NULL,
  `hr_atracao` TIME NOT NULL,
  `dt_registro_atracao` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `diretorio_img_atracao` VARCHAR(100) NOT NULL,
  `id_evento` INT(11) NOT NULL,
  PRIMARY KEY (`id_atracao`),
  INDEX `fk_Atracao_eventos1_idx` (`id_evento` ASC) ,
  CONSTRAINT `fk_Atracao_eventos1`
    FOREIGN KEY (`id_evento`)
    REFERENCES `events4u`.`eventos` (`id_evento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `events4u`.`usuarios_eventos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `events4u`.`usuarios_eventos` (
  `id_usuario` INT NOT NULL,
  `id_evento` INT(11) NOT NULL,
  `dt_hr_registro` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (`id_usuario`, `id_evento`),
  INDEX `fk_usuarios_has_eventos_eventos1_idx` (`id_evento` ASC) ,
  INDEX `fk_usuarios_has_eventos_usuarios1_idx` (`id_usuario` ASC) ,
  CONSTRAINT `fk_usuarios_has_eventos_usuarios1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `events4u`.`usuarios` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuarios_has_eventos_eventos1`
    FOREIGN KEY (`id_evento`)
    REFERENCES `events4u`.`eventos` (`id_evento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `events4u`.`folder`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `events4u`.`folder` (
  `id_folder` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `diretorio` VARCHAR(100) NOT NULL,
  `data_upload` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `id_evento` INT(11) NOT NULL,
  PRIMARY KEY (`id_folder`),
  INDEX `fk_folder_eventos1_idx` (`id_evento` ASC) ,
  CONSTRAINT `fk_folder_eventos1`
    FOREIGN KEY (`id_evento`)
    REFERENCES `events4u`.`eventos` (`id_evento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `events4u`.`patrocinador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `events4u`.`patrocinador` (
  `id_patrocinador` INT NOT NULL AUTO_INCREMENT,
  `nm_patrocinador` VARCHAR(50) NOT NULL,
  `diretorio_img_patrocinador` VARCHAR(100) NOT NULL,
  `dt_registro_patrocinador` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `id_evento` INT(11) NOT NULL,
  PRIMARY KEY (`id_patrocinador`),
  INDEX `fk_patrocinador_eventos1_idx` (`id_evento` ASC) ,
  CONSTRAINT `fk_patrocinador_eventos1`
    FOREIGN KEY (`id_evento`)
    REFERENCES `events4u`.`eventos` (`id_evento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `events4u`.`usuarios_solicita`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `events4u`.`usuarios_solicita` (
  `id_solicita` INT NOT NULL AUTO_INCREMENT,
  `id_evento` INT(11) NOT NULL,
  `id_usuario` INT NOT NULL,
  `dt_hr_registro` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (`id_solicita`),
  INDEX `fk_usuario_solicita_eventos1_idx` (`id_evento` ASC) ,
  INDEX `fk_usuario_solicita_usuarios1_idx` (`id_usuario` ASC) ,
  CONSTRAINT `fk_usuario_solicita_eventos1`
    FOREIGN KEY (`id_evento`)
    REFERENCES `events4u`.`eventos` (`id_evento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_solicita_usuarios1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `events4u`.`usuarios` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
